import './globals.css'
import type { Metadata } from 'next'
import { Roboto, Roboto_Condensed } from 'next/font/google'
import Script from 'next/script'

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
  display: 'swap',
  weight: ['100', '400', '500']
})
const roboto_condensed = Roboto_Condensed({
  subsets: ['latin'],
  variable: '--font-roboto-condensed',
  display: 'swap',
  weight: ['400', '700']
})

export const metadata: Metadata = {
  title: 'Frontend Developer Jorge Rondón',
  description: 'Generated by create next app',
}


export default function RootLayout({children,}: {children: React.ReactNode}) {


  return (
    <html lang="en" className={`${roboto.variable} ${roboto_condensed.variable} bg-neutral-900`}>

      <head>
          <Script
          id="google-tag-manager"
          strategy="lazyOnload" 
          src={`https://www.googletagmanager.com/gtm.js?id=G-FKPTBY45WN`}
        />
      </head>
      <body className={`${roboto.className} `}>
      <noscript>
          {`
            <iframe
              src="https://www.googletagmanager.com/ns.html?id=G-FKPTBY45WN"
              height="0"
              width="0"
              style="display:none;visibility:hidden"
            ></iframe>
          `}
        </noscript>
        
        
        
        {children}</body>


    </html>
  )
}
