import './globals.css'
import type { Metadata } from 'next'
import { Roboto, Roboto_Condensed } from 'next/font/google'
import Script from 'next/script'

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
  display: 'swap',
  weight: ['100', '400', '500']
})
const roboto_condensed = Roboto_Condensed({
  subsets: ['latin'],
  variable: '--font-roboto-condensed',
  display: 'swap',
  weight: ['400', '700']
})

export const metadata: Metadata = {
  title: 'Frontend Developer Jorge Rondón',
  description: 'Generated by create next app',
}


export const GTM_ID = 'G-FKPTBY45WN'

export default function RootLayout({children,}: {children: React.ReactNode}) {


  return (
    <html lang="en" className={`${roboto.variable} ${roboto_condensed.variable} bg-neutral-900`}>

      <head>
      <Script
          strategy="lazyOnload"
          src={`https://www.googletagmanager.com/gtm.js?id=${GTM_ID}`}
        />
          <script
              dangerouslySetInnerHTML={{
                __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
                new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
                j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
                'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
                })(window,document,'script','dataLayer','${GTM_ID}');`,
              }}
            />
      </head>
      <body className={`${roboto.className} `}>
        
       
        <noscript>
          {`
            <iframe
              src="https://www.googletagmanager.com/ns.html?id=${GTM_ID}"
              height="0"
              width="0"
              style="display:none;visibility:hidden"
            ></iframe>
          `}
        </noscript>
        
        
        
        {children}</body>


    </html>
  )
}
