import './globals.css'
import type { Metadata } from 'next'
import { Roboto, Roboto_Condensed } from 'next/font/google'

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
  display: 'swap',
  weight: ['100', '400', '500']
})
const roboto_condensed = Roboto_Condensed({
  subsets: ['latin'],
  variable: '--font-roboto-condensed',
  display: 'swap',
  weight: ['400', '700']
})

export const metadata: Metadata = {
  title: 'Frontend Developer Jorge Rondón',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${roboto.variable} ${roboto_condensed.variable} bg-dark-600`}>
      <body className={`${roboto.className} gradient-linear-dark`}>{children}</body>
    </html>
  )
}
